deltalab

alter system set db_create_file_dest='/u02/oradata' scope=both;
alter system set db_create_online_log_dest_1='/u02/oradata' scope=both;
alter system set db_recovery_file_dest_size=100g scope=both;
alter system set db_recovery_file_dest='/u02/oradata' scope=both;

    ALTER SESSION SET CONTAINER = CDB$ROOT;
CREATE PLUGGABLE DATABASE deltalabb ADMIN USER pdbadmin IDENTIFIED BY "pdbadmin";


137.131.239.145
Service "deltalabb" has 1 instance(s).
  Instance "deltalab", status READY, has 1 handler(s) for this service...


deltalab =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 137.131.239.145)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = deltalabb)
    )
  )

ALTER USER system IDENTIFIED BY "Ya-laZ8z#1";         
ALTER USER sys IDENTIFIED BY "Ya-laZ8z#1";

    ALTER PLUGGABLE DATABASE deltalabb OPEN;
    ALTER PLUGGABLE DATABASE deltalabb SAVE STATE;

CREATE BIGFILE TABLESPACE "USERS" DATAFILE SIZE 10m AUTOEXTEND ON NEXT 50m MAXSIZE 10g;
CREATE BIGFILE TEMPORARY TABLESPACE "TEMP" TEMPFILE SIZE 10m AUTOEXTEND ON NEXT 50m MAXSIZE 10g;
  
CREATE USER "SVC_DBA" IDENTIFIED BY "SVC_DBA_01"
      DEFAULT TABLESPACE "USERS"
      TEMPORARY TABLESPACE "TEMP";
 ALTER USER "SVC_DBA" LOCAL TEMPORARY TABLESPACE "TEMP";


GRANT GRANT ANY OBJECT PRIVILEGE TO SVC_DBA;
-- GRANT REVOKE ANY OBJECT PRIVILEGE TO SVC_DBA;

   ALTER USER "SVC_DBA" DEFAULT ROLE ALL;


=============================
CREATE USER "TESTE01" IDENTIFIED BY "TESTE01" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
CREATE USER "TESTE02" IDENTIFIED BY "TESTE02" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
CREATE USER "TESTE03" IDENTIFIED BY "TESTE03" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
CREATE USER "TESTE04" IDENTIFIED BY "TESTE04" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
CREATE USER "TESTE05" IDENTIFIED BY "TESTE05" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";

CREATE TABLE TESTE01.TB_TESTE01 
(
  COLUMN1 VARCHAR2(20) 
);

=====================
-- Forçar execução para teste
BEGIN
  DBMS_SCHEDULER.run_job(job_name => 'SVC_DBA.JOB_AUTO_REVOKE_GRANTS');
END;
/



sqlplus [USERNAME]/[PASSWORD]@[//]HOST[:PORT][/SERVICE_NAME]
sqlplus /nolog
conn sys@//137.131.239.145:1521/deltalabb