version: '3.8'

services:
  jira-web:
    build: .
    container_name: jira-web-dashboard
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    command: python3 src/app.py

  jira-notifier:
    build: .
    container_name: jira-notifier
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    command: python3 src/jira_to_teams.py
